[package]
name = "prompt"
version = "0.1.0"
authors = ["justinwoo <moomoowoo@gmail.com>"]
edition = "2018"

[dependencies]
termcolor = { git = "https://github.com/justinwoo/termcolor", branch = "non-printing-escape" }
git2 = "0.8"